language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements-dev.txt
  - pip install .
# command to run tests
script:
  - make unittest
  - make flake8
addons:
  apt:
    packages:
      - libgnome-keyring-dev
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true