language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements-dev.txt
  - pip install .
# command to run tests
script:
  - make unittest
  - make flake8

sudo: required
addons:
  apt:
    packages:
      - python-gnomekeyring
      - gnome-keyring

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true