#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# pylint: disable=C0103
"""CLI Main for OSENV Tool.

Links:
    https://realpython.com/command-line-interfaces-python-argparse/

Later:
    bash-completion
    https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2
    
    https://github.com/kislyuk/argcomplete/
"""
import argparse
import signal
import sys

from lib import __version__, _program, _description
from lib.osenv_controller import OSEnvController


def signal_handler(sig, frame):
    print("\nYou pressed Ctrl+C. Abort!")
    sys.exit(0)

def main(arguments):
    """Arguments control action."""
    if args.environment is not None:
        OSEnvController.action_environment(arguments)
    elif args.list is not False:
        OSEnvController.action_list()
    elif args.clean is not False:
        OSEnvController.action_clean()
    elif args.read is not None:
        OSEnvController.action_read(arguments)
    elif args.write is not None:
        OSEnvController.action_write(arguments)
    elif args.edit is not None:
        OSEnvController.action_edit(arguments)
    else:
        sys.exit(1)
    sys.exit()


if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal_handler)

    # create the top-level parser
    parser = argparse.ArgumentParser(
        prog=_program, description=_description
    )

    ###
    group = parser.add_mutually_exclusive_group(required=True)

    group.add_argument(
        "--version",
        action="version",
        version="{program} {version}".format(program=_program, version=__version__),
    )

    group.add_argument(
        "-e",
        "--environment",
        metavar="<environment-name>",
        help="Load .ostackrc environment name.",
    )
    group.add_argument(
        "-l",
        "--list",
        action="store_true",
        help="List available .ostackrc environments.",
    )
    group.add_argument(
        "-c",
        "--clean",
        action="store_true",
        help="Clean up active .ostackrc environment.",
    )
    group.add_argument(
        "-r",
        "--read",
        nargs="?",
        const="~/.ostackrc.enc",
        metavar="<encoded-file>",
        help="""Read encoded file and set content to session variables.
        Default filename is ~/.ostackrc.enc.""",
    )
    group.add_argument(
        "-w",
        "--write",
        nargs="?",
        const="~/.ostackrc.enc",
        type=str,
        metavar="<encoded-file>",
        help="""Create and write encoded file with multiple ostackrc
        environments. Default filename is ~/.ostackrc.enc.""",
    )
    group.add_argument(
        "-i",
        "--edit",
        nargs="?",
        const="~/.ostackrc.enc",
        metavar="<encoded-file>",
        help="""Edit a encoded file and write it back.
        Default filename is ~/.ostackrc.enc.""",
    )
    ###

    # Execute the parse_args() method
    args = parser.parse_args()
    sys.exit(main(args))
