"""OSENV CLI Tool."""
_program = "osenv-tool"
_description = "Create and load .ostackrc credentials confidentialy."
_author = "opnmind"
_url = "https://github.com/opnmind/osenv-tool"
__version__ = "0.7.0"
